version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/marketdata:/app/marketdata
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
