version: "3.8"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app            # Sync ganzen Code rein (ok für Dev)
      - ./marketdata:/app/marketdata  # Persistente Daten (z.B. SQLite DB)
    restart: always
    environment:
      - INSIDE_DOCKER=1   # WICHTIG für Product_Orchestrator
