version: "3.8"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./marketdata:/app/marketdata
    restart: always